### ISSUE TITLE
PHP 8.0 Listed twice

### ISSUE THREAD

**Issue by vmitchell85** [spatie/laravel-artisan-dd#17]
I doubt it breaks anything but PHP ^8.0 is listed twice in the composer.json file. I'm on mobile so I can't PR a fix right now.

![image](https://user-images.githubusercontent.com/1248035/143770601-b13bbf9f-dfdb-4cbe-b905-db022e3a1408.jpeg)

**Comment by freekmurze** [comment]
Fixed, thanks for reporting.
